// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/LoginTypes.txt
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/LoginTypes.txt</summary>
public static partial class LoginTypesReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/LoginTypes.txt</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static LoginTypesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRwcm90by9Mb2dpblR5cGVzLnR4dCpICgpMb2dpblR5cGVzEg4KCkxPR0lO",
          "X0NSRVEQABIOCgpMT0dJTl9TUkVTEAESDAoIUkVHX0NSRVEQAhIMCghSRUdf",
          "U1JFUxADYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LoginTypes), }, null, null));
  }
  #endregion

}
#region Enums
public enum LoginTypes {
  /// <summary>
  ///客户端申请登录
  /// </summary>
  [pbr::OriginalName("LOGIN_CREQ")] LoginCreq = 0,
  /// <summary>
  ///服务器反馈给客户端 登录结果
  /// </summary>
  [pbr::OriginalName("LOGIN_SRES")] LoginSres = 1,
  /// <summary>
  ///客户端申请注册
  /// </summary>
  [pbr::OriginalName("REG_CREQ")] RegCreq = 2,
  /// <summary>
  ///服务器反馈给客户端 注册结果
  /// </summary>
  [pbr::OriginalName("REG_SRES")] RegSres = 3,
}

#endregion


#endregion Designer generated code
