// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/MatchTypes.txt
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/MatchTypes.txt</summary>
public static partial class MatchTypesReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/MatchTypes.txt</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MatchTypesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRwcm90by9NYXRjaFR5cGVzLnR4dCpiCgpNYXRjaFR5cGVzEg4KCkVOVEVS",
          "X0NSRVEQABIOCgpFTlRFUl9TUkVTEAESDgoKTEVBVkVfQ1JFURACEg4KCkxF",
          "QVZFX1NSRVMQAxIUChBFTlRFUl9TRUxFQ1RfQlJPEARiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MatchTypes), }, null, null));
  }
  #endregion

}
#region Enums
public enum MatchTypes {
  /// <summary>
  ///申请进入匹配
  /// </summary>
  [pbr::OriginalName("ENTER_CREQ")] EnterCreq = 0,
  /// <summary>
  ///返回申请结果
  /// </summary>
  [pbr::OriginalName("ENTER_SRES")] EnterSres = 1,
  /// <summary>
  ///申请离开匹配
  /// </summary>
  [pbr::OriginalName("LEAVE_CREQ")] LeaveCreq = 2,
  /// <summary>
  ///返回离开结果
  /// </summary>
  [pbr::OriginalName("LEAVE_SRES")] LeaveSres = 3,
  /// <summary>
  ///匹配完毕，通知进入 选择界面广播
  /// </summary>
  [pbr::OriginalName("ENTER_SELECT_BRO")] EnterSelectBro = 4,
}

#endregion


#endregion Designer generated code
