// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/Types.txt
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/Types.txt</summary>
public static partial class TypesReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/Types.txt</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static TypesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9wcm90by9UeXBlcy50eHQqSQoITXNnVHlwZXMSDgoKVFlQRV9MT0dJThAA",
          "Eg0KCVRZUEVfVVNFUhABEg4KClRZUEVfTUFUQ0gQAhIOCgpUWVBFX0ZJR0hU",
          "EANiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MsgTypes), }, null, null));
  }
  #endregion

}
#region Enums
public enum MsgTypes {
  [pbr::OriginalName("TYPE_LOGIN")] TypeLogin = 0,
  [pbr::OriginalName("TYPE_USER")] TypeUser = 1,
  [pbr::OriginalName("TYPE_MATCH")] TypeMatch = 2,
  [pbr::OriginalName("TYPE_FIGHT")] TypeFight = 3,
}

#endregion


#endregion Designer generated code
