// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/UserTypes.txt
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/UserTypes.txt</summary>
public static partial class UserTypesReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/UserTypes.txt</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static UserTypesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNwcm90by9Vc2VyVHlwZXMudHh0Km0KCVVzZXJUeXBlcxINCglJTkZPX0NS",
          "RVEQABINCglJTkZPX1NSRVMQARIPCgtDUkVBVEVfQ1JFURACEg8KC0NSRUFU",
          "RV9TUkVTEAMSDwoLT05MSU5FX0NSRVEQBBIPCgtPTkxJTkVfU1JFUxAFYgZw",
          "cm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::UserTypes), }, null, null));
  }
  #endregion

}
#region Enums
public enum UserTypes {
  /// <summary>
  ///获取自身数据
  /// </summary>
  [pbr::OriginalName("INFO_CREQ")] InfoCreq = 0,
  /// <summary>
  ///返回自身数据
  /// </summary>
  [pbr::OriginalName("INFO_SRES")] InfoSres = 1,
  /// <summary>
  ///申请创建角色
  /// </summary>
  [pbr::OriginalName("CREATE_CREQ")] CreateCreq = 2,
  /// <summary>
  ///返回创建结果
  /// </summary>
  [pbr::OriginalName("CREATE_SRES")] CreateSres = 3,
  /// <summary>
  ///用户上线
  /// </summary>
  [pbr::OriginalName("ONLINE_CREQ")] OnlineCreq = 4,
  /// <summary>
  ///返回用户上线
  /// </summary>
  [pbr::OriginalName("ONLINE_SRES")] OnlineSres = 5,
}

#endregion


#endregion Designer generated code
